# Problem Set: Numpy Basics - Array creation and manipulation
Do a File, Save a copy in Drive to make this your own.  You'll submit this problem set by sharing a link.  *Make sure to enable commenting when you share*.

 ***Note, if I ask you to print something, use the `print` command.  But, if I ask you to create another variable, insert something into a variable, etc., do not just use `print`. I want you to create things or change their values, not just show them on the screen.***

Q1: Create a matrix **A** that looks like this

| <!-- --> | <!-- --> | <!-- --> | <!-- --> |
|----|----|----|----|
| 1 | 2 | 3 | 4 |
| 10 | 20 | 30 | 40 | 
| 100 | 200 | 300 | 400 |



In [ ]:
import numpy as np


Q2: Now, create a matrix **B** that looks like this and by using **A**

| <!-- --> | <!-- --> | <!-- --> | 
|----|----|----|
| 1 | 10 | 100 |
| 2 | 20 | 200 | 
| 3 | 30 | 300 |
| 4 | 40 | 400 |

Q3: Now, create a matrix **C** that uses **A** and looks like this

| <!-- --> | <!-- --> | <!-- --> | <!-- --> |
|----|----|----|----|
| 1 | 2 | 3 | 4 |
| 10 | 20 | **25** | 40 | 
| 100 | 200 | 300 | 400 |

Q4: Create a **D** in which each element is equal to twice the value in **A** plus the value in **C**

Q5: Create an **E** in which each element is equal to the value from **A** times the value from **C**

Q6: Figure out how the zeros or ones functions work to make a matrix **F** that is 32x32 with the value of pi in each element.

Q7: Make an array **G** that is the corners of **A** and do so in one statement (use start:stop:stride).  That is, it should be:
```
array([[ 1, 4], 
[100, 400]])
```


Q8: Make a 1D array **H** that uses **A** and contains all of the elements of **A** that are evenly divisible by 4 (doing this might make you *mod* at me).  That is, it should be:

```
array([  4,  20,  40, 100, 200, 300, 400])
```


Q9: Assume **E** is the result of some math calculating the number of degrees between two items in the distance.  You don't want things like 400 degrees of angle to be specified, or you'll look stupid.  Use the `np.mod` or `%` operator to convert **E** into standard 0-359 degree numbers and store this in **I**. 

Q10: Make an 1D array **J** that has the mean value for each column of **A**.  That is, it should be

```
array([  37.,   74.,  111.,  148.])
```