# Problem Set 3: Finding bad values
In this problem set, you will write two functions:
    
Write a function `FindBadValuesSingleColumn` that will take as input:

- a filename (two samples are given here)
- a column number
- a threshold value
    
The function should return the rows in which the value in which 
that column's value exceeds the threshold.  Return this as an 
np.array.  

Note:
- Use NumPy and not Pandas for this
- Yes, you must deal with the fact that the 'tsv' file has a header
- Handle columns with nan values treating them as 0
- Look at `np.genfromtxt` and `np.argwhere`

Example:
```
FindBadValuesSingleColumn(fname1,0,0.75)
array([[  1],
       [ 16],
       [ 76],
       [ 82],
       [102],
       [115],
       [116],
       [143],
       [151],
       [152]])
    

FindBadValuesSingleColumn(fname1,5,0.2)
array([[122],
       [123],
       [125],
       [127],
       [158],
       [159]])

FindBadValuesSingleColumn(fname2,5,0.2)
array([[184],
       [186]])
```

Write a second function, `FindBadValuesTwoColumns` that is like the above but takes:
- a filename
- a list of two columns (or tuple)
- a list of two thresholds

The function should return an `np.array` of all the indicies
in which either threshold is exceeded.  So, if c0>t0 _OR_ if
c1>t1 it gets flagged.  Thus, it should be longer than either
alone.

Example:
```
FindBadValuesTwoColumns(fname1,(0,5),(0.75,0.2))
array([  1,  16,  76,  82, 102, 115, 116, 122, 123, 125, 127, 143, 151,
       152, 158, 159])
```

In [69]:
import numpy as np
fname1='https://raw.githubusercontent.com/celstark/n247data/main/data/sub-s2_ses-Day1_task-4min_bold_confounds.tsv'
fname2='https://raw.githubusercontent.com/celstark/n247data/main/data/sub-s2_ses-Day1_task-5min_bold_confounds.tsv'

def FindBadValuesSingleColumn(fname,column,threshold): 
        f = np.genfromtxt(fname=fname, skip_header=1, filling_values=0) #use np.genfromtxt to skip header and set N/A values to 0  
        column_data = f[:, column]
        
        #return all INDICES where threshold is exceeded. use np.argwhere to return non-zero values
        threshold_exceeded = np.argwhere(column_data > threshold)

        return np.array(threshold_exceeded)

In [70]:

def FindBadValuesTwoColumns(fname,columns,thresholds): 
    '''parameters: filename, list or tuple of 2 columns, list or tuple of 2 thresholds'''
    c0, c1 = columns
    t0, t1 = thresholds

    f = np.genfromtxt(fname=fname, skip_header=1, filling_values=0) #use np.genfromtxt to skip header and set N/A values to 0  
    column_data_0= f[:, c0]
    column_data_1= f[:, c1]
        
    threshold_exceeded_0 = np.argwhere(column_data_0 > t0) #return all INDICES where threshold is exceeded for column 0. use np.argwhere to return non-zero values
    threshold_exceeded_1 = np.argwhere(column_data_1 > t1) #return all INDICES where threshold is exceeded for column 1. use np.argwhere to return non-zero values


    #merge the 2 arrays for each column
    threshold_exceeded = np.concatenate((threshold_exceeded_0, threshold_exceeded_1))

    return np.array(threshold_exceeded) 