# Problem Set 3: Finding bad values
In this problem set, you will write two functions:
    
Write a function `FindBadValuesSingleColumn` that will take as input:

- a filename (two samples are given here)
- a column number
- a threshold value
    
The function should return the rows in which the value in which 
that column's value exceeds the threshold.  Return this as an 
np.array.  

Note:
- Use NumPy and not Pandas for this
- Yes, you must deal with the fact that the 'tsv' file has a header
- Handle columns with nan values treating them as 0
- Look at `np.genfromtxt` and `np.argwhere`

Example:
```
FindBadValuesSingleColumn(fname1,0,0.75)
array([[  1],
       [ 16],
       [ 76],
       [ 82],
       [102],
       [115],
       [116],
       [143],
       [151],
       [152]])
    

FindBadValuesSingleColumn(fname1,5,0.2)
array([[122],
       [123],
       [125],
       [127],
       [158],
       [159]])

FindBadValuesSingleColumn(fname2,5,0.2)
array([[184],
       [186]])
```

Write a second function, `FindBadValuesTwoColumns` that is like the above but takes:
- a filename
- a list of two columns (or tuple)
- a list of two thresholds

The function should return an `np.array` of all the indicies
in which either threshold is exceeded.  So, if c0>t0 _OR_ if
c1>t1 it gets flagged.  Thus, it should be longer than either
alone.

Example:
```
FindBadValuesTwoColumns(fname1,(0,5),(0.75,0.2))
array([  1,  16,  76,  82, 102, 115, 116, 122, 123, 125, 127, 143, 151,
       152, 158, 159])
```

In [12]:
import numpy as np
fname1='https://raw.githubusercontent.com/celstark/n247data/main/data/sub-s2_ses-Day1_task-4min_bold_confounds.tsv'
fname2='https://raw.githubusercontent.com/celstark/n247data/main/data/sub-s2_ses-Day1_task-5min_bold_confounds.tsv'

def FindBadValuesSingleColumn(fname,column,threshold): 
        f = np.genfromtxt(fname=fname, skip_header=1, filling_values=0) #use np.genfromtxt to skip header and set N/A values to 0  
        print(f[column])
    
        
        #return all indicies where threshold is exceeded
        threshold_exceeded = [n for n in f[column] if n > threshold]
        print(threshold_exceeded)

        threshold_exceeded = np.argwhere(threshold_exceeded) #use np.argwhere to return non-zero values 


        return np.array(threshold_exceeded)




In [13]:
FindBadValuesSingleColumn(fname1,0,0.75)

[-2.27147579e-01  1.82726049e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -8.92735331e-02 -8.46620350e-02
  2.70626621e-02 -4.43224860e-03  4.11377727e-02 -7.41831483e-02
 -9.60537957e-02 -7.90956686e-02  5.99410043e-02 -4.52791670e-02
  3.33848968e-02 -1.03051682e-02  1.11798011e-01  1.11781848e-01
  2.03571000e-02 -2.34229000e-02 -8.24316000e-03  1.52932000e-03
  1.99960000e-04 -8.66781000e-04]
[1.8272604942321775]


array([[0]])

In [ ]:

def FindBadValuesTwoColumns(fname,columns,thresholds): 
    '''parameters: filename, list of 2 columns, list of 2 thresholds'''
    c0, c1 = columns
    t0, t1 = thresholds
    with open(fname, 'r') as file:
        #use np.genfromtxt to skip header 
        #handle columns with nan values -- treat them as zero 
        #use np.argwhere to return non-zero values 



        #return all indicies where threshold is exceeded
        threshold_exceeded = [n for n in c0 ]


    return np.array(threshold_exceeded)