# Conventions

To get started, you will need to import the functions from NumPy.  By convention, this is:


```
import numpy as np
```


Later on, we'll bring in other bits like Matplotlib's plotting routines


```
from matplotlib import pyplot as plt
```


All of my code will assume that you've imported things this way and not just done


```
import numpy
```


If you do that, you'll need to reference things like


```
numpy.array()
```


and not


```
np.array()
```


Just so I don't get called out by the geek police, a quick disclaimer.  You'll see me talk about a "numpy array", and use `np.array`, but you'll also see me talk about `np.ndarray`.  I'll use them interchangeably and truth be told, the first and third of those are the same and `np.array` is a touch different.  The class that NumPy makes for us is called an "ndarray" or N-dimensional array.  A standard way of creating an object of this class is to use the function `np.array([1,2,3,4])` or something similar.  You could also create it with `np.zeros(2)` for example to make a 2x2 array of zeros (see below).  In talking about things, I'll equate the terms though as it hardly matters to you and it's a pain to say "n-d-array" all the time.  But, if you see things talking about "ndarray", it's just the NumPy array we know and love.




# Creating arrays

You can create arrays much like you created lists, but you need to tell Python it's a numpy array as this aren't baked into Python. To make a 1-dimensional array (aka vector, aka rank 1 array)


```
z=np.array([1,2,3,4])
```


So you're calling the function `np.array`, which needs the parentheses, and you're passing in a list in brackets to let it know what the array should hold

To make a 2D array (note all the brackets here):


```
z=np.array([[1,2,3],[4,5,6]])
```


Same deal here, but now we pass in a list of lists, hence the brackets around the two bracketed lists

You also have a number of nice built-in functions to create pre-made arrays filled with zeros, ones, or whatever you like.


```
z=np.zeros((3,2))
```


This will make an `np.array` of all zeros that has 3 rows and 2 columns. Why the extra parentheses?  Well, `np.zeros` takes several parameters and one of them is the shape -- the 3x2.  Here, we need one value -- one "shape" value -- to have both aspects of the size, so we make a tuple `(3,2)` and that tuple, being a single thing, takes the first parameter slot to `np.zeros()`

Want ones and not zeros?


```
np.ones((3,2))
```


Want it filled with pi?


```
np.full((3,2),np.pi)
```


or


```
np.ones((3,2)) * np.pi
```


Want it just generically empty?


```
np.empty((3,2))
```



***Exercise: Make an array that has 4 columns and 2 rows and is filled with the number 42. Use the cell below.***  

In [1]:
import numpy as np

np.full((2,4), 42)

array([[42, 42, 42, 42],
       [42, 42, 42, 42]])

## The Make it Like X functions

If you know you want something the same size/shape of an existing array, you could grab the size of the existing one using `foo.shape()` and do something like `np.ones(foo.shape())` but NumPy has nice shorthands:


```
np.zeros_like(existing_item)
np.ones_like(existing_item)
np.empty_like(existing_item)
```


Note, `empty_like()` and `empty()` will often give the same result as `zeros_like()` and `zeros()`, but the values aren't explicitly forced to be anything.  So, you could get random crud.  But, it's faster as it's not enforcing everything must be set to 0.  So, if you're going to overwrite it anyway, feel free to use `empty()` or `empty_like()`

You might think you can copy an array using the "=" operator as in:


```
a=np.array([1,2,3])
b=a
```


The problem here is if you do something like


```
b[0]=999
b
array([999, 2, 3])
a
array([999, 2, 3])
```


What we've done here is create b as a "view" of a, not an actual copy.  If you want to make an explicit copy of a and store it in b we need to:


```
b=a.copy()
```


Why on earth might this be desired?  This is called creating a new "view" of the data, here by slicing it.  Maybe you want just one plane of a 3D dataset or something.  It's a nice shorthand.


```
a=np.array([1,2,3,4])
b=a[1:3]
b
array([2, 3])
b[0]=10
a
array([ 1, 10,  3,  4])
```

Before running this cell, what do you think each of those `print` statements will print?

In [2]:
import numpy as np
a=np.array([1,2,3])
b=a
c=a.copy()
print(a,b,c)
b[1]=10
print(a,b,c)
c[1]=20
print(a,b,c)


[1 2 3] [1 2 3] [1 2 3]
[ 1 10  3] [ 1 10  3] [1 2 3]
[ 1 10  3] [ 1 10  3] [ 1 20  3]


## Data types

NumPy arrays are really nice for math and for >1 dimensions, but they have a real limitation when compared to Python's lists.  They can only be of one "type".  A Python list can be:


```
a = [4, 'dog', 3.14, [1, 2]]
```


NumPy arrays, not so much.  You're talking integers `(np.int`) or floating point numbers (`np.float`).  In general, NumPy will convert for you as needed, but if you ever need to deal with converting to another type, you'll do something like:


```
a=np.array([1,2,3,4])
a=a.astype(np.float)
```


OR


```
a=np.array([1,2,3,4], dtype=np.float)
```





# Indexing arrays

Getting bits of an array is just like getting bits of a list.  We use the same `[ ]` operations, we have _start:stop:stride_ kinds of mechanisms, etc.


```
z=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
z[2,3]
12
z[0,:]
array([1, 2, 3, 4])
z[0:2,:]
array([[1, 2, 3, 4],
[5, 6, 7, 8]]
z[1,0:3:2]
array([5, 7])
```


You can get funky here if you want and pass in arrays as your indices. 


```
r=[0,2]
z[r,3]
array([ 4, 12])
```


So here, we got the 0,3 element (4) and the 2,3 element (12). You can have both of them as rank-1 arrays (vectors) and get out the points like this:


```
c=[1,3]
z[r,c]
array([ 2, 12])
```
Here's a simple example.  Create a `b` that has the middle two values from the middle row of `a` and print it out

In [ ]:
import numpy as np
a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


# Create a "b" that has the middle two values from the middle row of "a" and print it out (aka 6 and 7)
b = a[1, 1:3]
print(b)


[6 7]


## Logical indexing

If you have a variable that codes True / False for each element, you can grab just the True elements.  Let's say, for example, that you wanted all of the elements of our array here that are greater than some threshold (>= 10) or that are odd numbers.  If we can define arrays that code for this, we can then select just those values.  For example:


In [5]:
import numpy as np
z=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
big = z >= 10
odd = (z % 2) == 1
print('Big ones...')
print(z[big])
print('Odd ones')
print(z[odd])

Big ones...
[10 11 12]
Odd ones
[ 1  3  5  7  9 11]


Note, in this, you're looking at that odd odd line and wondering what's up with the **%**?  That's the _modulo_ operator and one of my personal favorites (yes, I have favorite operators).  What it means is "do integer division and tell me the remainder".  Described like that, it doesn't seem all that useful.  But, if I told you to turn right 370 degrees, you'd ask "why not just turn right 10 degrees"?  Modulo helps here.  `370 % 360` is 10.  In the case above, dividing by 2 and looking at the remainder tells you if it's odd or even.  What if we wanted to assign our 10 rats in an experiment to 4 conditions?  You could say "if it's 1-4, condition 1, 5-8 and it's condition 2, etc." or you could say `RatNum % 4`.  (This would make them 0-3 so deal with that or just add 1).  Really, really handy operator.

In the cell below, in one line, print out the even entries of `z`

In [7]:
import numpy as np
z=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# In one line below, print out the even entries of z
print(z[(z % 2) == 0])


[ 2  4  6  8 10 12]


# Math 'n stuff

In general, math happens element-wise.  So, if we had our example from above


```
z=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
```


We could double each value with:


```
z * 2
array([[ 2, 4, 6, 8],
[10, 12, 14, 16],
[18, 20, 22, 24]])
```


Now, technically this is something called an "overload" and, internally, the "*" gets remapped from Python's "*" to `np.multiply(z,2)`, but you can safely ignore this for now.  (This all comes from everything being an object.  For `np.array` objects, "*" mean element-wise multiplication and "+" means element-wise addition.  _Remember how "+" meant "concatenate these lists" in Python lists and not actual addition?_)

We have the standard +, -, /, and * operators.  We also have ** for exponents.  We have a lot more though.  Have a look [at the list here](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

We have a lot of great methods (functions) we can apply to anything that's an np.ndarray For example, you have things like


```
z.sum()
78
```


For this (and many others), you can specify an axis to operate on.  For example


```
z.sum(0)
array([15, 18, 21, 24])
```



```
z.sum(1)
array([10, 26, 42])
```


You also have:

*   `.max([axis])`: Maximum either globally or along an axis
*   `.min([axis])`: Minimum either globally or along an axis
*   `.mean([axis])`: Mean value either globally or along an axis
*   `cumsum([axis])`: Cumulative sum either globally or along an axis
*   ...


# Random useful bits


## Array information


*   `.ndim`: # of dimensions
*   `.shape`: tuple giving the size of each dimension
*   `.size`: Total number of elements


## Shape

*   `.reshape`: Return a new array with the specified shape.  If `a.size` returned (2,3), we could rotate it with b=a.reshape((3,2)).  We could make it 1D by `b=a.reshape((1,6))` or even cooler with `b=a.reshape(1,-1)`.  The -1 here means "fill in the right value based on the size".
*   `.resize`: Like reshape, but do so destructively
*   `.transpose`: Transpose the matrix (rows become columns)


## Other



*   `np.linspace(start, stop [,number])`: Create a 1D array that has _number_ evenly-spaced values from _start_ to _stop_
*   `np.arange([start,] stop[, step,])`: Very similar to np.linspace but this is like Python's _start:stop:stride_ syntax and you're specifying the stride vs. the # of steps.

***Exercises***
Make an np-array that's 5 rows and 2 columns with the first column being the numbers 1-5 and the second column being 2,4,6,8,10.  Print this to the screen.  

Next, figure the sum across each axis separately and print that.

Finally, use logical indexing to find and print all the odd elements.


In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5], [2,4,6,8,10]]).transpose()
print(a)

print("sum of all columns for axis 0:", a.sum(0))
print("sum of all rows for axis 1:", a.sum(1))

#print all odd elements
a[(a % 2 != 0)] 



[[ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]]
sum of all columns for axis 0: [15 30]
sum of all rows for axis 1: [ 3  6  9 12 15]


array([1, 3, 5])